# Generated by Django 5.0.6 on 2024-10-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skills_aghs_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='is_facet',
            field=models.BooleanField(default=False),
        ),
    ]
